In [1]:
import pandas as pd

In [2]:
school_data_to_load = "Resources/schools_complete.csv"
school_data = pd.read_csv(school_data_to_load)
school_data.head()

FileNotFoundError: [Errno 2] File Resources/schools_complete.csv does not exist: 'Resources/schools_complete.csv'

In [3]:
student_data_to_load = "Resources/students_complete.csv"
student_data = pd.read_csv(student_data_to_load)
student_data.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [4]:
school_student_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name","school_name"])
school_student_data_complete.columns

Index(['Student ID', 'student_name', 'gender', 'grade', 'school_name',
       'reading_score', 'math_score', 'School ID', 'type', 'size', 'budget'],
      dtype='object')

In [31]:
#Calculate the total number of schools
#Calculate the total number of students
#Calculate the total budget
#Calculate the average math score 
#Calculate the average reading score
#Calculate the percentage of students with a passing math score (70 or greater)
#Calculate the percentage of students with a passing reading score (70 or greater)
#Calculate the percentage of students who passed math and reading (% Overall Passing)
#Create a dataframe to hold the above results

#Optional: give the displayed data cleaner formatting

school_count = len(school_data["school_name"].unique())
student_count = len(student_data["Student ID"].unique())
total_budget = school_data["budget"].sum()
avg_math_score = student_data["math_score"].mean()
avg_reading_score = student_data["reading_score"].mean()

passing_math_score = len(student_data.loc[student_data["math_score"]>=70])
passing_math = passing_math_score / student_count
passing_math_percent = passing_math * 100

passing_reading_score = len(student_data.loc[student_data["reading_score"]>=70])
passing_reading = passing_reading_score / student_count
passing_reading_percent = passing_reading * 100

passing_math_reading_score = len(student_data.loc[(student_data["math_score"]>=70) & (student_data["reading_score"]>=70)])
                              
passing_overall = passing_math_reading_score / student_count

passing_overall_percent = passing_overall * 100

district_summary = pd.DataFrame ({
    "Total Schools" : [school_count],
    "Total Students" : [student_count],
    "Total Budget" : [ total_budget],
    "Average Math Score" : [avg_math_score],
    "Average Reading Score" : [avg_reading_score],
    "Percent Passing Math" : [passing_math_percent],
    "Percent Passing Reading" : [passing_reading_percent],
    "Percent Overall Passing" : [passing_overall_percent
                                ]})

district_summary

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,Percent Passing Math,Percent Passing Reading,Percent Overall Passing
0,15,39170,24649428,78.985371,81.87784,74.980853,85.805463,65.172326

In [57]:
#School Name
#School Type
#Total Students
#Total School Budget
#Per Student Budget
#Average Math Score
#Average Reading Score
#% Passing Math (The percentage of students that passed math.)
#% Passing Reading (The percentage of students that passed reading.)
#% Overall Passing (The percentage of students that passed math **and** reading.)

school_groupby = school_student_data_complete.groupby("school_name")
school_means = school_groupby.mean()

school_type = school_data.set_index('school_name')
school_type = school_type['type']

school_total_students = school_means['size']
school_total_budget = school_means['budget']

per_student_budget = school_total_budget / school_total_students

school_avg_math_score = school_means['math_score']
school_avg_reading_score = school_means['reading_score']

school_counts = school_groupby.count()
school_counts_math = school_student_data_complete.loc[school_student_data_complete["math_score"]>=70]
school_counts_reading = school_student_data_complete.loc[school_student_data_complete["reading_score"]>=70]

school_counts_math_groupby = school_counts_math.groupby("school_name").count()["student_name"]
passing_math = school_counts_math_groupby / school_total_students
passing_math_percent = passing_math * 100

school_counts_reading_groupby = school_counts_reading.groupby("school_name").count()["student_name"]
passing_reading = school_counts_reading_groupby / school_total_students
passing_reading_percent = passing_reading * 100

passing_math_reading_score = len(school_student_data_complete.loc[(school_student_data_complete["math_score"]>=70) & (school_student_data_complete["reading_score"]>=70)])                             
passing_overall = passing_math_reading_score / school_total_students
passing_overall_percent = passing_overall * 100


school_summary = pd.DataFrame ({
    #"School Name" : school_groupby,
    "School Type" : school_type,
    "Total Students" : school_total_students,
    "Total School Budget" : school_total_budget,
    "Per Student Budget" : per_student_budget,
    "Average Math Score" : school_avg_math_score,
    "Average Reading Score" : school_avg_reading_score,
    "Percent Passing Math" : passing_math_percent,
    "Percent Passing Reading" : passing_reading_percent,
    "Percent Overall Passing" : passing_overall_percent
                    })

school_summary

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,Percent Passing Math,Percent Passing Reading,Percent Overall Passing
Bailey High School,District,4976.0,3124928.0,628.0,77.048432,81.033963,66.680064,81.933280,513.022508
Cabrera High School,Charter,1858.0,1081356.0,582.0,83.061895,83.975780,94.133477,97.039828,1373.950484
Figueroa High School,District,2949.0,1884411.0,639.0,76.711767,81.158020,65.988471,80.739234,865.649373
Ford High School,District,2739.0,1763916.0,644.0,77.102592,80.746258,68.309602,79.299014,932.018985
Griffin High School,Charter,1468.0,917500.0,625.0,83.351499,83.816757,93.392371,97.138965,1738.964578
Hernandez High School,District,4635.0,3022020.0,652.0,77.289752,80.934412,66.752967,80.862999,550.765912
Holden High School,Charter,427.0,248087.0,581.0,83.803279,83.814988,92.505855,96.252927,5978.454333
Huang High School,District,2917.0,1910635.0,655.0,76.629414,81.182722,65.683922,81.316421,875.145698
Johnson High School,District,4761.0,3094650.0,650.0,77.072464,80.966394,66.057551,81.222432,536.189876
Pena High School,Charter,962.0,585858.0,609.0,83.839917,84.044699,94.594595,95.945946,2653.638254
Rodriguez High School,District,3999.0,2547363.0,637.0,76.842711,80.744686,66.366592,80.220055,638.359590
Shelton High School,Charter,1761.0,1056600.0,600.0,83.359455,83.725724,93.867121,95.854628,1449.630892
Thomas High School,Charter,1635.0,1043130.0,638.0,83.418349,83.848930,93.272171,97.308869,1561.345566
Wilson High School,Charter,2283.0,1319574.0,578.0,83.274201,83.989488,93.867718,96.539641,1118.177836
Wright High School,Charter,1800.0,1049400.0,583.0,83.682222,83.955000,93.333333,96.611111,1418.222222

In [58]:
#Create a table that highlights the top 5 performing schools based on % Overall Passing. Include:

school_summary.sort_values(by="Percent Overall Passing", ascending=False)

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,Percent Passing Math,Percent Passing Reading,Percent Overall Passing
Holden High School,Charter,427.0,248087.0,581.0,83.803279,83.814988,92.505855,96.252927,5978.454333
Pena High School,Charter,962.0,585858.0,609.0,83.839917,84.044699,94.594595,95.945946,2653.638254
Griffin High School,Charter,1468.0,917500.0,625.0,83.351499,83.816757,93.392371,97.138965,1738.964578
Thomas High School,Charter,1635.0,1043130.0,638.0,83.418349,83.848930,93.272171,97.308869,1561.345566
Shelton High School,Charter,1761.0,1056600.0,600.0,83.359455,83.725724,93.867121,95.854628,1449.630892
Wright High School,Charter,1800.0,1049400.0,583.0,83.682222,83.955000,93.333333,96.611111,1418.222222
Cabrera High School,Charter,1858.0,1081356.0,582.0,83.061895,83.975780,94.133477,97.039828,1373.950484
Wilson High School,Charter,2283.0,1319574.0,578.0,83.274201,83.989488,93.867718,96.539641,1118.177836
Ford High School,District,2739.0,1763916.0,644.0,77.102592,80.746258,68.309602,79.299014,932.018985
Huang High School,District,2917.0,1910635.0,655.0,76.629414,81.182722,65.683922,81.316421,875.145698
Figueroa High School,District,2949.0,1884411.0,639.0,76.711767,81.158020,65.988471,80.739234,865.649373
Rodriguez High School,District,3999.0,2547363.0,637.0,76.842711,80.744686,66.366592,80.220055,638.359590
Hernandez High School,District,4635.0,3022020.0,652.0,77.289752,80.934412,66.752967,80.862999,550.765912
Johnson High School,District,4761.0,3094650.0,650.0,77.072464,80.966394,66.057551,81.222432,536.189876
Bailey High School,District,4976.0,3124928.0,628.0,77.048432,81.033963,66.680064,81.933280,513.022508

In [59]:
#Create a table that highlights the bottom 5 performing schools based on % Overall Passing.

school_summary.sort_values(by="Percent Overall Passing", ascending=True)

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,Percent Passing Math,Percent Passing Reading,Percent Overall Passing
Bailey High School,District,4976.0,3124928.0,628.0,77.048432,81.033963,66.680064,81.933280,513.022508
Johnson High School,District,4761.0,3094650.0,650.0,77.072464,80.966394,66.057551,81.222432,536.189876
Hernandez High School,District,4635.0,3022020.0,652.0,77.289752,80.934412,66.752967,80.862999,550.765912
Rodriguez High School,District,3999.0,2547363.0,637.0,76.842711,80.744686,66.366592,80.220055,638.359590
Figueroa High School,District,2949.0,1884411.0,639.0,76.711767,81.158020,65.988471,80.739234,865.649373
Huang High School,District,2917.0,1910635.0,655.0,76.629414,81.182722,65.683922,81.316421,875.145698
Ford High School,District,2739.0,1763916.0,644.0,77.102592,80.746258,68.309602,79.299014,932.018985
Wilson High School,Charter,2283.0,1319574.0,578.0,83.274201,83.989488,93.867718,96.539641,1118.177836
Cabrera High School,Charter,1858.0,1081356.0,582.0,83.061895,83.975780,94.133477,97.039828,1373.950484
Wright High School,Charter,1800.0,1049400.0,583.0,83.682222,83.955000,93.333333,96.611111,1418.222222
Shelton High School,Charter,1761.0,1056600.0,600.0,83.359455,83.725724,93.867121,95.854628,1449.630892
Thomas High School,Charter,1635.0,1043130.0,638.0,83.418349,83.848930,93.272171,97.308869,1561.345566
Griffin High School,Charter,1468.0,917500.0,625.0,83.351499,83.816757,93.392371,97.138965,1738.964578
Pena High School,Charter,962.0,585858.0,609.0,83.839917,84.044699,94.594595,95.945946,2653.638254
Holden High School,Charter,427.0,248087.0,581.0,83.803279,83.814988,92.505855,96.252927,5978.454333

In [ ]:
#Create a table that lists the average Math Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

In [ ]:
#Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

In [ ]:
#Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:

#Average Math Score
#Average Reading Score
#% Passing Math (The percentage of students that passed math.)
#% Passing Reading (The percentage of students that passed reading.)
#% Overall Passing (The percentage of students that passed math **and** reading.)

In [ ]:
#Repeat the above breakdown, but this time group schools based on a reasonable approximation of school size (Small, Medium, Large).

In [ ]:
#Repeat the above breakdown, but this time group schools based on school type (Charter vs. District).